// <auto-generated />
using System;
using HvZ.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HvZ.Migrations
{
    [DbContext(typeof(HvZDbContext))]
    [Migration("20230320104126_AddUsernameDb")]
    partial class AddUsernameDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("HvZ.Model.Domain.ChatDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("ChatTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHumanGlobal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZombieGlobal")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int?>("SquadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("SquadId");

                    b.ToTable("Chats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1079),
                            GameId = 1,
                            IsHumanGlobal = true,
                            IsZombieGlobal = false,
                            Message = "One zombie close to me",
                            PlayerId = 2,
                            SquadId = 1
                        },
                        new
                        {
                            Id = 2,
                            ChatTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1082),
                            GameId = 1,
                            IsHumanGlobal = false,
                            IsZombieGlobal = true,
                            Message = "Surround that human",
                            PlayerId = 1,
                            SquadId = 2
                        },
                        new
                        {
                            Id = 3,
                            ChatTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1083),
                            GameId = 2,
                            IsHumanGlobal = true,
                            IsZombieGlobal = false,
                            Message = "Need help!",
                            PlayerId = 3,
                            SquadId = 1
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.GameDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameState")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<double?>("Nw_Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Nw_Lng")
                        .HasColumnType("float");

                    b.Property<double?>("Se_Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Se_Lng")
                        .HasColumnType("float");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Human vs Zombie fun",
                            GameState = "Registration",
                            Name = "First Game",
                            Nw_Lat = 40.753,
                            Nw_Lng = 73.983000000000004,
                            StartTime = new DateTime(2023, 3, 20, 11, 41, 26, 34, DateTimeKind.Local).AddTicks(700)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Very fun game join plz!",
                            GameState = "In Progress",
                            Name = "Second Game",
                            Se_Lat = 33.924900000000001,
                            Se_Lng = 18.424099999999999,
                            StartTime = new DateTime(2023, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.KillDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("KillerId")
                        .HasColumnType("int");

                    b.Property<double?>("Lat")
                        .HasColumnType("float");

                    b.Property<double?>("Lng")
                        .HasColumnType("float");

                    b.Property<string>("Story")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("TimeOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<int>("VictimId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("KillerId");

                    b.HasIndex("VictimId");

                    b.ToTable("Kills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            KillerId = 1,
                            Lat = 33.321300000000001,
                            Lng = 24.222999999999999,
                            Story = "Stabbed him very hard",
                            TimeOfDeath = new DateTime(2023, 3, 9, 6, 30, 0, 0, DateTimeKind.Unspecified),
                            VictimId = 2
                        },
                        new
                        {
                            Id = 2,
                            GameId = 2,
                            KillerId = 1,
                            Lat = 23.3828,
                            Lng = 82.992000000000004,
                            Story = "Shot him in the face",
                            TimeOfDeath = new DateTime(2023, 3, 9, 6, 30, 30, 0, DateTimeKind.Unspecified),
                            VictimId = 3
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.MissionDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHumanVisible")
                        .HasColumnType("bit");

                    b.Property<bool>("IsZombieVisible")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Missions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Find a sock to equip yourself",
                            EndTime = new DateTime(2023, 3, 20, 11, 11, 26, 34, DateTimeKind.Utc).AddTicks(1108),
                            GameId = 1,
                            IsHumanVisible = true,
                            IsZombieVisible = false,
                            Name = "Gather",
                            StartTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1108)
                        },
                        new
                        {
                            Id = 2,
                            Description = "Survive the horde of zombies for 15 minutes ",
                            EndTime = new DateTime(2023, 3, 20, 10, 56, 26, 34, DateTimeKind.Utc).AddTicks(1113),
                            GameId = 2,
                            IsHumanVisible = true,
                            IsZombieVisible = false,
                            Name = "Survive",
                            StartTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1112)
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kill 5 humans within 45 minutes ",
                            EndTime = new DateTime(2023, 3, 20, 11, 26, 26, 34, DateTimeKind.Utc).AddTicks(1114),
                            GameId = 2,
                            IsHumanVisible = false,
                            IsZombieVisible = true,
                            Name = "Blood bath",
                            StartTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1114)
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.PlayerDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BiteCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPatientZero")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BiteCode = "231233",
                            GameId = 1,
                            IsHuman = false,
                            IsPatientZero = true,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            BiteCode = "112334",
                            GameId = 1,
                            IsHuman = true,
                            IsPatientZero = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            BiteCode = "928475",
                            GameId = 2,
                            IsHuman = true,
                            IsPatientZero = false,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadCheckInDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<double>("Lat")
                        .HasColumnType("float");

                    b.Property<double>("Lng")
                        .HasColumnType("float");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.Property<int>("SquadMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("SquadId");

                    b.HasIndex("SquadMemberId");

                    b.ToTable("SquadCheckIns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new DateTime(2023, 3, 20, 11, 26, 26, 34, DateTimeKind.Utc).AddTicks(1193),
                            GameId = 1,
                            Lat = 55.229999999999997,
                            Lng = 20.100999999999999,
                            SquadId = 1,
                            SquadMemberId = 1,
                            StartTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1192)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new DateTime(2023, 3, 20, 11, 11, 26, 34, DateTimeKind.Utc).AddTicks(1198),
                            GameId = 1,
                            Lat = 10.987,
                            Lng = 40.500999999999998,
                            SquadId = 2,
                            SquadMemberId = 2,
                            StartTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1198)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new DateTime(2023, 3, 20, 10, 51, 26, 34, DateTimeKind.Utc).AddTicks(1200),
                            GameId = 2,
                            Lat = 70.566999999999993,
                            Lng = 5.1109999999999998,
                            SquadId = 1,
                            SquadMemberId = 3,
                            StartTime = new DateTime(2023, 3, 20, 10, 41, 26, 34, DateTimeKind.Utc).AddTicks(1199)
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHuman")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Squads");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            IsHuman = true,
                            Name = "Dream team"
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            IsHuman = true,
                            Name = "Survivors"
                        },
                        new
                        {
                            Id = 3,
                            GameId = 1,
                            IsHuman = false,
                            Name = "Kill all humans"
                        },
                        new
                        {
                            Id = 4,
                            GameId = 2,
                            IsHuman = false,
                            Name = "Zombie zombie"
                        },
                        new
                        {
                            Id = 5,
                            GameId = 2,
                            IsHuman = true,
                            Name = "Win win"
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadMemberDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SquadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.HasIndex("SquadId");

                    b.ToTable("SquadMembers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            GameId = 1,
                            PlayerId = 2,
                            Rank = "General",
                            SquadId = 1
                        },
                        new
                        {
                            Id = 2,
                            GameId = 1,
                            PlayerId = 3,
                            Rank = "Soldier",
                            SquadId = 2
                        },
                        new
                        {
                            Id = 3,
                            GameId = 2,
                            PlayerId = 1,
                            Rank = "Super Zombie",
                            SquadId = 4
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.UserDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Håvard",
                            IsAdmin = false,
                            LastName = "Madland",
                            UserName = "Hav"
                        },
                        new
                        {
                            Id = 2,
                            FirstName = "An",
                            IsAdmin = false,
                            LastName = "Nguyen",
                            UserName = "Al"
                        },
                        new
                        {
                            Id = 3,
                            FirstName = "Vilhelm",
                            IsAdmin = false,
                            LastName = "Assersen",
                            UserName = "Will"
                        });
                });

            modelBuilder.Entity("HvZ.Model.Domain.ChatDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("Chats")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.PlayerDomain", "Player")
                        .WithMany("Chats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.SquadDomain", "Squad")
                        .WithMany("Chats")
                        .HasForeignKey("SquadId");

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("HvZ.Model.Domain.KillDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("Kills")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.PlayerDomain", "Killer")
                        .WithMany("Kills")
                        .HasForeignKey("KillerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.PlayerDomain", "Victim")
                        .WithMany()
                        .HasForeignKey("VictimId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Killer");

                    b.Navigation("Victim");
                });

            modelBuilder.Entity("HvZ.Model.Domain.MissionDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("Missions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HvZ.Model.Domain.PlayerDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.UserDomain", "User")
                        .WithMany("Players")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadCheckInDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("SquadCheckIns")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.SquadDomain", "Squad")
                        .WithMany("SquadCheckIns")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.SquadMemberDomain", "SquadMember")
                        .WithMany("SquadCheckIns")
                        .HasForeignKey("SquadMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Squad");

                    b.Navigation("SquadMember");
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("Squads")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadMemberDomain", b =>
                {
                    b.HasOne("HvZ.Model.Domain.GameDomain", "Game")
                        .WithMany("SquadMembers")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.PlayerDomain", "Player")
                        .WithOne("SquadMember")
                        .HasForeignKey("HvZ.Model.Domain.SquadMemberDomain", "PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HvZ.Model.Domain.SquadDomain", "Squad")
                        .WithMany("SquadMembers")
                        .HasForeignKey("SquadId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Player");

                    b.Navigation("Squad");
                });

            modelBuilder.Entity("HvZ.Model.Domain.GameDomain", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Kills");

                    b.Navigation("Missions");

                    b.Navigation("Players");

                    b.Navigation("SquadCheckIns");

                    b.Navigation("SquadMembers");

                    b.Navigation("Squads");
                });

            modelBuilder.Entity("HvZ.Model.Domain.PlayerDomain", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Kills");

                    b.Navigation("SquadMember");
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadDomain", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("SquadCheckIns");

                    b.Navigation("SquadMembers");
                });

            modelBuilder.Entity("HvZ.Model.Domain.SquadMemberDomain", b =>
                {
                    b.Navigation("SquadCheckIns");
                });

            modelBuilder.Entity("HvZ.Model.Domain.UserDomain", b =>
                {
                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
